desc "Start the server"
task :default do
  exec 'bundle exec shotgun --server thin --host 0.0.0.0 --port 3000'
end

desc "Compile coffeescript and SCSS files"
task :compile do
  Thread.new { `coffee -w -c -o public views/kubrick.coffee` }
  Thread.new { `sass --watch views/kubrick.scss:public/kubrick.css --scss --load-path views --style compressed --no-cache` }.join
end